spring.application.name=OrderManagement
orders.input-folder=file:/Users/shemida/Downloads/Batches/input
orders.archive-folder=file:/Users/shemida/Downloads/Batches/output
orders.is-create-folders=false
logging.level.org.springframework.jdbc.datasource.init=DEBUG
server.port=8010
spring.batch.job.enabled=false
spring.active.profiles=local,tempfolders
spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:mem:orderMgmtdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.jdbc=DEBUG
security.jwt.secret-key=f37H26qbluVZEkcVpUaUQaTbB4kBEsPB+VkvVKfWfOY=
# 1h in millisecond
security.jwt.expiration-time=3600000
spring.mvc.problemdetails.enabled=true
