DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    LOCATION VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRODUCT(
    PRODUCT_CODE VARCHAR(255) PRIMARY KEY,
    COST DECIMAL(10, 2),
    STATUS VARCHAR(255)
);

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION) VALUES (10001, 'Tony', 'Stark', 'tony.stark@gmail.com', 'Australia');
INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION) VALUES (10002, 'Bruce', 'Banner', 'bruce.banner@gmail.com', 'US');
INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION) VALUES (10003, 'Steve', 'Rogers', 'steve.rogers@gmail.com', 'Australia');
INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION) VALUES (10004, 'Wanda', 'Maximoff', 'wanda.maximoff@gmail.com', 'US');
INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION) VALUES (10005, 'Natasha', 'Romanoff', 'natasha.romanoff@gmail.com', 'Canada');

INSERT INTO PRODUCT (PRODUCT_CODE, COST, STATUS) VALUES ('PRODUCT_001', 50, 'Active');
INSERT INTO PRODUCT (PRODUCT_CODE, COST, STATUS) VALUES ('PRODUCT_002', 100, 'Inactive');
INSERT INTO PRODUCT (PRODUCT_CODE, COST, STATUS) VALUES ('PRODUCT_003', 200, 'Active');
INSERT INTO PRODUCT (PRODUCT_CODE, COST, STATUS) VALUES ('PRODUCT_004', 10, 'Inactive');
INSERT INTO PRODUCT (PRODUCT_CODE, COST, STATUS) VALUES ('PRODUCT_005', 500, 'Active');