DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    LOCATION VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRODUCT(
    PRODUCT_CODE VARCHAR(255) PRIMARY KEY,
    COST DECIMAL(10, 2),
    STATUS VARCHAR(255)
);